### ISSUE TITLE
What's the point of this?

### ISSUE THREAD

**Issue by ioncodes** [Jodel/Jodel-Backend-Challenge#1]
I'm not sure what this is, I just found it... Is this intended to be some sort of proof of our skills if we apply for a job? Isn't the task actually how you fetch jodels from your server?

I just had to make this issue, I got a bit curious when I saw this repo ^^

**Comment by ldb** [comment]
Yes, this challenge is part of our hiring process.
You can check our currently open positions [on our jobs page](https://jodel.com/jobs/).
